---
title: ""
author: Laraib Azmat
date: June 06, 2024
format: html
---

```{r library read in}
library(tidyverse)
library(readr)
library(readxl)
```

```{r}
#reading in data from data folder
edu_data <- read_csv("./data/EDU01a.csv")

#reading specs of table to get column names
spec(edu_data)
```

```{r}
#saving edits as a new object
edu_edit <- edu_data |>
  #selecting only area_name, STCOU, and the columns that end with "D"
  select(Area_name, STCOU, ends_with("D")) |>
  rename("area_name" = "Area_name")

  #printing to see the results 
  print()|>
  #converting to a long form and moving the results to an "enlorment" column
  pivot_longer(cols = 3:12, 
               values_to = "enlorment")
#printing to see the results
edu_edit
```

```{r}
#overwriting the object to save edits
edu_edit <- edu_edit |>
  #changing the values to reflect years using the data information sheet
  mutate( year = case_when(
    name == "EDU010187D" ~ 1987, 
    name == "EDU010188D" ~ 1988, 
    name == "EDU010189D" ~ 1989, 
    name == "EDU010190D" ~ 1990, 
    name == "EDU010191D" ~ 1991, 
    name == "EDU010192D" ~ 1992, 
    name == "EDU010193D" ~ 1993, 
    name == "EDU010194D" ~ 1994, 
    name == "EDU010195D" ~ 1995, 
    name == "EDU010196D" ~ 1996
  )) |>
  #creating a new column to represent which measurement grabbed
  mutate(measurement = substr(edu_edit$name, 1, 7))

#printing to see the results
edu_edit
```

```{r}
#creating new data set with county level data 
edu_county <- subset(edu_edit, grepl(pattern = ", \\w\\w", edu_edit$Area_name))

#overwriting the county object to save edits 
edu_county <- edu_county |>
  #adding a new column to represent county's state
  mutate(state = str_extract(edu_county$Area_name, " \\w\\w")) |>
  #adjusting columns to look better
  select(Area_name, state, STCOU, name, measurement, year, everything())

#changing the class of the county data set
class(edu_county) <- c("county", class(edu_county))

#printing the data set
edu_county
```

```{r}
#creating new data set with state level data
edu_state <- subset(edu_edit, !(grepl(pattern = ", \\w\\w", edu_edit$Area_name)))

#adjusting area_name values to easily identify the region
edu_state$Area_name <- str_to_title(edu_state$Area_name)

#adding new column to reflect division of the state
edu_state$division <- as.character(setNames(state.division, state.name)[edu_state$Area_name])

#overwriting the state object to save edits 
edu_state <- edu_state |>
#fixing division data to reflect error condition and  
    mutate(division = case_when(
      Area_name == "District Of Columbia" ~ "South Atlantic", 
      is.na(division) ~ "ERROR"
      )) |>
  #adjusting columns to look better
  select(Area_name, division, STCOU, everything())

#printing the data set
edu_state
```




Writing The Function:
First, reading in the second data set:
```{r}
edu_data_b <- read_csv("./data/EDU01b.csv")

#reading specs of table to get column names
#spec(edu_data_b)
```
Write one function that does steps 1 & 2 above. Give an optional argument (that is it has a default value) that allows the user to specify the name of the column representing the value (enrollment for these data sets).
```{r}
steps_1_and_2 <- function(data, value = "enrollment"){

# selecting the appropriate columns
  selected_columns <- data |>
       select(Area_name, STCOU, ends_with("D")) |>
       rename("area_name" = "Area_name")
  
# pivoting the data, 'value' is defaulted to enrollment but can be changed
  pivoted_data <- selected_columns |> 
       pivot_longer(cols = 3:ncol(selected_columns), 
               values_to = value)
  
# returning the data 
  return(pivoted_data)
}
```

testing the function
```{r}
after_step_2 <- steps_1_and_2(data = edu_data_b, value = "test")
after_step_2
```

Writing function for step 3:
```{r}
step_3 <- function(data){
  
edit <- data |>
  #first we have to create a column corresponding to the last 2 digits
   mutate(last_2_digits =  substr(name,8,9),
  #then we will use logic to say if these are bigger than 24 the year must be in the 1900s
         year = ifelse(last_2_digits > 24, 
                       paste("19",last_2_digits, sep = ""), 
                       paste("20",last_2_digits, sep = "")),
         measurement = substr(data$name, 1, 7)) |>
  select(-last_2_digits)
return(edit)
}
```

testing function for step 3:
```{r}
after_step_3 <- step_3(data = after_step_2)
after_step_3
```



